import { Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

// Shared marker for content generated by the backend's AI services (Insights
// Digest, Dispatch Assistant) — kept visually distinct from the rest of the
// app's neutral palette so users can tell at a glance which numbers came
// from a model vs. a direct query.
export function AiBadge({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        "border-primary/25 bg-primary/10 text-primary inline-flex h-5 w-fit shrink-0 items-center gap-1 rounded-full border px-2 py-0.5 text-[11px] font-semibold tracking-wide uppercase",
        className,
      )}
    >
      <Sparkles className="size-3" />
      AI
    </span>
  );
}
